/**
 * Build 42 item-script generation for the Mod Generator.
 *
 * This is the generator's own B42 emission layer: it produces
 * `ItemType = base:*` item blocks (the Build 42 item-class model) instead of
 * the legacy `Type = ...` model, writes display names into the Build 42
 * `ItemName` translation file instead of a `DisplayName` property, and only
 * ever emits properties declared by the template — so nothing leaks in from
 * ScriptGenerator's legacy templates (review item: "simple_item coupling").
 */

import type { ModgenTemplate } from "./templates.js";

/** Structural slice of ModgenBlueprint needed to render script + translation. */
export interface BlueprintLike {
  mod: {
    module: string;
    itemName: string;
    displayName: string;
    modName: string;
    icon: string;
  };
  stats: Record<string, any>;
}

function fmtValue(v: unknown): string {
  if (typeof v === "boolean") return v ? "TRUE" : "FALSE";
  return String(v);
}

/**
 * Render the item script block:
 *
 *   module Base
 *   {
 *       item MyItem
 *       {
 *           ItemType = base:weapon,
 *           DisplayCategory = Weapon,
 *           Weight = 1.5,
 *           ...
 *           Icon = Axe,
 *           WeaponSprite = Axe,
 *       }
 *   }
 */
const SAFE_MODULE = /^[A-Za-z0-9_]+$/;

/** Module names must be identifier-safe; fall back to Base otherwise. */
export function safeModule(module: string): string {
  return SAFE_MODULE.test(module) ? module : "Base";
}

export function buildItemScript(
  tpl: ModgenTemplate,
  blueprint: BlueprintLike,
): string {
  const m = blueprint.mod;
  const lines: string[] = [];
  lines.push("/**");
  lines.push(` * ${m.modName} — generated by the pz-mcp-server Mod Generator.`);
  lines.push(` * Build 42 item script (ItemType class: ${tpl.itemType}).`);
  lines.push(" */");
  lines.push(`module ${safeModule(m.module)}`);
  lines.push("{");
  lines.push(`    item ${m.itemName}`);
  lines.push("    {");
  lines.push(`        ItemType = ${tpl.itemType},`);
  if (tpl.displayCategory) {
    lines.push(`        DisplayCategory = ${tpl.displayCategory},`);
  }
  for (const field of tpl.fields) {
    const v = blueprint.stats[field.key];
    if (v === undefined || v === null || v === "") continue;
    lines.push(`        ${field.key} = ${fmtValue(v)},`);
  }
  lines.push(`        Icon = ${m.icon},`);
  if (tpl.emitWeaponSprite) {
    lines.push(`        WeaponSprite = ${m.icon},`);
  }
  lines.push("    }");
  lines.push("}");
  return lines.join("\n") + "\n";
}

/**
 * Build 42 item display names live in the ItemName translation file, keyed by
 * the item's full type `Module.ItemId` (verified against the 42.20 install:
 * media/lua/shared/Translate/EN/ItemName.json → { "Base.3030Box": "..." }).
 */
export function buildItemTranslation(blueprint: BlueprintLike): string {
  const m = blueprint.mod;
  const key = `${safeModule(m.module)}.${m.itemName}`;
  return JSON.stringify({ [key]: m.displayName }, null, 4) + "\n";
}

export const ITEM_NAME_TRANSLATION_PATH =
  "42/media/lua/shared/Translate/EN/ItemName.json";

/** Sanitize an icon name so it is safe to use as a texture filename. */
export function safeIconFileName(icon: string): string | null {
  if (!/^[A-Za-z0-9_]+$/.test(icon)) return null;
  return `${icon}.png`;
}
