/**
 * Dependency-free parser for generated JavaDoc HTML (javadoc ≥ 17 output,
 * "ClassWriter" pages). The Project Zomboid JavaDocs corpus is generated by
 * JDK 25 javadoc, so this targets that exact markup: `<meta name="generator"
 * content="javadoc/ClassWriter">` identifies a class page, `class="detail"`
 * sections carry member signatures, `<span class="modifiers|return-type|
 * element-name|parameters">` structure the signatures, `class="inheritance"`
 * holds the type hierarchy, and `class="block"`/`<dt>` blocks hold javadoc
 * prose.
 *
 * Everything here is pure string processing on raw HTML — no DOM, no
 * third-party deps — so it runs anywhere Node runs and is trivially testable.
 */
import type {
  JavaDocClass,
  JavaDocKind,
  JavaDocMember,
  JavaDocMemberKind,
  JavaDocParam,
} from "./types.js";

/** Generator meta value that marks a real per-type API page. */
export const CLASS_WRITER_GENERATOR = "javadoc/ClassWriter";

/** Simple named entities the javadoc output uses. */
const NAMED_ENTITIES: Record<string, string> = {
  nbsp: " ",
  amp: "&",
  lt: "<",
  gt: ">",
  quot: '"',
  apos: "'",
  ndash: "–",
  mdash: "—",
  hellip: "…",
  copy: "©",
  reg: "®",
  trade: "™",
  bull: "•",
};

/** Decode `&amp;`, `&#35;` / `&#x23;` style entities to plain text. */
export function decodeEntities(text: string): string {
  return text.replace(
    /&(#x?[0-9a-fA-F]+|[a-zA-Z][a-zA-Z0-9]*);/g,
    (match, ent) => {
      if (ent[0] === "#") {
        const code =
          ent[1] === "x" || ent[1] === "X"
            ? parseInt(ent.slice(2), 16)
            : parseInt(ent.slice(1), 10);
        if (Number.isFinite(code) && code >= 0) {
          try {
            return String.fromCodePoint(code);
          } catch {
            return match;
          }
        }
        return match;
      }
      return NAMED_ENTITIES[ent] ?? match;
    },
  );
}

/**
 * Render an HTML fragment to readable text: tags stripped (link/anchor text
 * kept), `<wbr>` dropped, `<br>` → newline, entities decoded, whitespace
 * collapsed per line.
 */
export function htmlText(html: string): string {
  const raw = html
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<wbr\s*\/?>/gi, "")
    .replace(/<[^>]+>/g, "");
  return decodeEntities(raw)
    .split("\n")
    .map((line) => line.replace(/\s+/g, " ").trim())
    .join("\n")
    .trim();
}

/**
 * Find the first HTML tag matching `openRe` at/after `from` and return the
 * balanced section content (same-named closing tag; nesting counted).
 * Returns null when no opening or matching close tag exists.
 */
export function extractBalanced(
  html: string,
  openRe: RegExp,
  from = 0,
): { start: number; end: number; content: string } | null {
  const open = openRe.exec(html.slice(from));
  if (!open) return null;
  const start = from + open.index;
  const openLen = open[0].length;
  const tagRe = /<\/?section\b[^>]*>/g;
  tagRe.lastIndex = start + openLen;
  let depth = 1;
  let match: RegExpExecArray | null;
  while ((match = tagRe.exec(html)) !== null) {
    if (match[0].startsWith("</section")) {
      depth -= 1;
      if (depth === 0) {
        const end = match.index + match[0].length;
        return { start, end, content: html.slice(start, end) };
      }
    } else {
      depth += 1;
    }
  }
  return null;
}

/** Content of the first `<span class="...">` whose class contains `name`. */
export function extractSpan(
  html: string,
  name: string,
  from = 0,
): string | null {
  const re = new RegExp(
    `<span\\b[^>]*class="[^"]*\\b${name}\\b[^"]*"[^>]*>`,
    "i",
  );
  const open = re.exec(html.slice(from));
  if (!open) return null;
  const start = from + open.index;
  const closeRe = /<\/span>/g;
  closeRe.lastIndex = start + open[0].length;
  const close = closeRe.exec(html);
  if (!close) return null;
  return html.slice(start + open[0].length, close.index);
}

/** Text of the first `<span class="...">` whose class contains `name`. */
export function extractSpanText(
  html: string,
  name: string,
  from = 0,
): string | null {
  const span = extractSpan(html, name, from);
  if (span === null) return null;
  const text = htmlText(span);
  return text.length > 0 ? text : null;
}

/**
 * Text of every `<span class="...">` whose class contains `name`, in order
 * (deprecated signatures render `@Deprecated` as its own modifier span
 * ahead of the real modifiers).
 */
export function extractSpansText(html: string, name: string): string[] {
  const results: string[] = [];
  const re = new RegExp(
    `<span\\b[^>]*class="[^"]*\\b${name}\\b[^"]*"[^>]*>`,
    "gi",
  );
  let match: RegExpExecArray | null;
  while ((match = re.exec(html)) !== null) {
    const closeRe = /<\/span>/g;
    closeRe.lastIndex = match.index + match[0].length;
    const close = closeRe.exec(html);
    if (!close) break;
    const text = htmlText(
      html.slice(match.index + match[0].length, close.index),
    );
    if (text.length > 0) results.push(text);
    re.lastIndex = close.index; // resume after the closing tag
  }
  return results;
}

/** `<meta name="generator" content="...">` value, if present. */
export function extractGenerator(html: string): string | null {
  const match = html.match(/<meta\s+name="generator"\s+content="([^"]+)"/i);
  return match ? match[1] : null;
}

/** A class page is one generated by javadoc/ClassWriter (API types only). */
export function isClassPage(html: string): boolean {
  return extractGenerator(html) === CLASS_WRITER_GENERATOR;
}

/** `declaration: package: zombie, class: ZomboidGlobals` from the meta description. */
export function extractDeclaration(html: string): {
  package: string;
  type: string;
} | null {
  const match = html.match(
    /<meta\s+name="description"\s+content="declaration:\s*package:\s*([^,]+),\s*(?:class|interface|enum|record|annotation type):\s*([^"]+)"/i,
  );
  if (!match) return null;
  return { package: match[1].trim(), type: match[2].trim() };
}

/** `Unofficial PZ JavaDocs 42.20.0` from the `.about-language` nav div. */
export function extractAboutLanguage(html: string): string | null {
  const match = html.match(/about-language">([^<]+)<\/div>/i);
  return match ? match[1].trim() : null;
}

/** The h1 `class="title"` text, e.g. `Class ZomboidGlobals`. */
export function extractTitle(html: string): string | null {
  const match = html.match(/<h1[^>]*class="title"[^>]*>([\s\S]*?)<\/h1>/i);
  return match ? htmlText(match[1]) : null;
}

/** Kind + simple name from the h1 title (e.g. `Enum Class AttackType`). */
export function parseTitle(title: string): { kind: JavaDocKind; name: string } {
  const lowered = title.toLowerCase();
  const kind: JavaDocKind = lowered.startsWith("interface ")
    ? "interface"
    : lowered.startsWith("enum ")
      ? "enum"
      : lowered.startsWith("record ")
        ? "record"
        : lowered.startsWith("annotation ")
          ? "annotation"
          : "class";
  // The kind prefix is "Enum Class " / "Record Class " / "Annotation Type "
  // — strip it case-insensitively but keep the rest intact.
  const name = title.replace(
    /^(Class|Interface|Enum Class|Record Class|Annotation Type)\s+/i,
    "",
  );
  return { kind, name: name.trim() };
}

/** Class-level `<div class="type-signature">` text (modifiers + name + hierarchy). */
export function extractTypeSignature(html: string): string | null {
  const match = html.match(/<div class="type-signature">([\s\S]*?)<\/div>/);
  return match ? htmlText(match[1]) : null;
}

/** `extends X` / `implements Y, Z` declarations from the type signature. */
export function parseExtendsImplements(signature: string): {
  superclass?: string;
  interfaces: string[];
} {
  const interfaces: string[] = [];
  let superclass: string | undefined;
  const implIdx = signature.indexOf("implements");
  const extIdx = signature.indexOf("extends");
  const first = (idx: number) => (idx === -1 ? Infinity : idx);
  if (first(extIdx) < first(implIdx)) {
    const after = signature.slice(extIdx + "extends".length);
    const end = implIdx === -1 ? after.length : after.indexOf("implements");
    superclass = after.slice(0, end).trim().split(/\s+/)[0] || undefined;
  }
  if (implIdx !== -1) {
    const after = signature.slice(implIdx + "implements".length);
    // Split on commas at top level (ignore commas inside generics).
    interfaces.push(
      ...splitTopLevel(after, ",")
        .map((s) => s.trim())
        .filter(Boolean),
    );
  }
  return { ...(superclass ? { superclass } : {}), interfaces };
}

/**
 * Split `text` on `separator` at nesting depth zero (angle brackets tracked),
 * so `Map<String, Integer> x` is not split inside the generics.
 */
export function splitTopLevel(text: string, separator: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let current = "";
  for (const ch of text) {
    if (ch === "<") depth += 1;
    else if (ch === ">") depth = Math.max(0, depth - 1);
    if (ch === separator && depth === 0) {
      parts.push(current);
      current = "";
    } else {
      current += ch;
    }
  }
  parts.push(current);
  return parts;
}

/** Inheritance chain (root → leaf) from the nested `.inheritance` divs. */
/**
 * Inheritance chain (root → leaf) from the nested `.inheritance` divs.
 * A balanced `<div>` scan of the outer `title="Inheritance Tree"` div makes
 * this robust for both multi-level chains (Object → … → type) and the
 * single-level chain an interface with no superinterfaces produces (a
 * lookahead would over-capture into the type-signature section below).
 */
export function extractInheritance(html: string): string[] {
  const openRe = /<div class="inheritance" title="Inheritance Tree">/;
  const open = openRe.exec(html);
  if (!open) return [];
  let depth = 1;
  const tagRe = /<\/?div\b[^>]*>/g;
  tagRe.lastIndex = open.index + open[0].length;
  let tag: RegExpExecArray | null;
  while ((tag = tagRe.exec(html)) !== null) {
    if (tag[0].startsWith("</div")) {
      depth -= 1;
      if (depth === 0) {
        const content = html.slice(open.index, tag.index);
        // Each nested `<div class="inheritance">` starts a new level.
        const levels = content
          .replace(/<div class="inheritance"/g, '\n<div class="inheritance"')
          .replace(/<\/div>/g, "</div>\n");
        return htmlText(levels)
          .split("\n")
          .map((line) => line.trim())
          .filter((line) => line.length > 0);
      }
    } else {
      depth += 1;
    }
  }
  return [];
}

/** Javadoc prose: first `<div class="block">` inside `region`. */
export function extractBlockText(html: string): string | null {
  const match = html.match(/<div class="block">([\s\S]*?)<\/div>/);
  if (!match) return null;
  const text = htmlText(match[1]);
  return text.length > 0 ? text : null;
}

/** Parse `<dt>Parameters:</dt><dd><code>name</code> - description</dd>` blocks. */
/**
 * Parse `<dt>Parameters:</dt><dd><code>name</code> - description</dd>` blocks:
 * collect every `<dd>` between this `<dt>` label and the next `<dt>` or
 * `</dl>`. Returns the dd texts (htmlToText'd).
 */
export function extractDefinitionList(html: string, label: string): string[] {
  const dtRe = new RegExp(`<dt>\\s*${label}\\s*:?\\s*</dt>`, "i");
  const dtMatch = dtRe.exec(html);
  if (!dtMatch) return [];
  const after = html.slice(dtMatch.index + dtMatch[0].length);
  const boundaryRe = /<\/dl>|<dt\b/g;
  const boundary = boundaryRe.exec(after);
  const block = boundary ? after.slice(0, boundary.index) : after;
  const results: string[] = [];
  const ddRe = /<dd>([\s\S]*?)<\/dd>/g;
  let dd: RegExpExecArray | null;
  while ((dd = ddRe.exec(block)) !== null) {
    results.push(htmlText(dd[1]));
  }
  return results;
}

/**
 * Parse a `name - description` entry (javadoc dt/dd convention) into its
 * leading code token and prose.
 */
export function parseParamEntry(entry: string): {
  name: string;
  description?: string;
} {
  const code = entry.match(/^`([^`]*)`\s*-\s*([\s\S]*)$/);
  if (code) {
    const description = code[2].trim();
    return {
      name: code[1].trim(),
      ...(description.length > 0 ? { description } : {}),
    };
  }
  const dash = entry.indexOf(" - ");
  if (dash !== -1) {
    const description = entry.slice(dash + 3).trim();
    return {
      name: entry.slice(0, dash).trim(),
      ...(description.length > 0 ? { description } : {}),
    };
  }
  return { name: entry.trim() };
}

/** Group id → member kind mapping for the `*-details` sections. */
function groupKind(groupId: string): JavaDocMemberKind | null {
  if (groupId.includes("field")) return "field";
  if (groupId.includes("constructor")) return "constructor";
  if (groupId.includes("method")) return "method";
  // Enum constants + record components are API knowledge too — model them
  // as fields (their member-signatures read `public static final X FOO`).
  if (
    groupId.includes("enum-constant") ||
    groupId.includes("record-component")
  ) {
    return "field";
  }
  return null;
}

/** Split a parameters span "(Type a, Type b)" into param objects. */
function parseParameterSpan(text: string): JavaDocParam[] {
  const inner = text.trim();
  if (!inner.startsWith("(") || !inner.endsWith(")")) return [];
  const body = inner.slice(1, -1).trim();
  if (body.length === 0) return [];
  const params: JavaDocParam[] = [];
  for (const part of splitTopLevel(body, ",")) {
    const trimmed = part.trim();
    if (trimmed.length === 0) continue;
    // `Type name` / `Type... name` → name is the final identifier (varargs
    // keeps its `...`). Generics (`Map<String, Integer>`) handled by split.
    const m = trimmed.match(/^([\s\S]*?)\s+([$\w][$\w]*)(\.\.\.)?$/);
    if (m && m[2]) {
      const type = (m[1] + (m[3] ?? "")).trim();
      params.push({
        name: m[2],
        ...(type.length > 0 ? { type } : {}),
      });
    } else {
      params.push({ name: trimmed.replace(/^@\S+\s*/, "").trim() });
    }
  }
  return params;
}

/** Parse one `<section class="detail" id="...">` member block. */
function parseMemberDetail(
  content: string,
  kind: JavaDocMemberKind,
): JavaDocMember | null {
  const nameMatch = content.match(/<h3>([\s\S]*?)<\/h3>/i);
  const sigMatch = content.match(
    /<div class="member-signature">([\s\S]*?)<\/div>/,
  );
  if (!nameMatch && !sigMatch) return null;

  const name = nameMatch ? htmlText(nameMatch[1]) : "";
  const sigHtml = sigMatch ? sigMatch[1] : "";
  const signature = htmlText(sigHtml);
  const modifiers = extractSpansText(sigHtml, "modifiers").join(" ");
  const returnType = extractSpanText(sigHtml, "return-type") ?? undefined;
  const paramsText = extractSpanText(sigHtml, "parameters");
  const parameters = paramsText !== null ? parseParameterSpan(paramsText) : [];
  const description = extractBlockText(content) ?? undefined;
  const deprecated =
    content.includes("deprecated-label") ||
    /@Deprecated/.test(signature) ||
    undefined;

  // Attach javadoc parameter descriptions (by name) where available.
  const paramEntries = extractDefinitionList(content, "Parameters");
  if (paramEntries.length > 0) {
    for (const param of parameters) {
      const entry = paramEntries
        .map(parseParamEntry)
        .find((e) => e.name === param.name);
      if (entry?.description && param.description === undefined) {
        param.description = entry.description;
      }
    }
  }

  return {
    kind,
    name,
    signature,
    modifiers,
    ...(returnType !== undefined ? { returnType } : {}),
    parameters,
    ...(description !== undefined ? { description } : {}),
    ...(deprecated ? { deprecated: true } : {}),
  };
}

/**
 * Parse a javadoc ClassWriter page into structured API knowledge.
 *
 * @param html raw page HTML
 * @param filePath absolute path of the page (used for error context + the
 *   package fallback when the meta declaration is missing)
 * @param relDir package-relative directory of the page (dots), used as the
 *   package when the page lacks a meta description (e.g. stripped docs)
 */
export function parseJavaDocClass(
  html: string,
  filePath: string,
  relDir = "",
): JavaDocClass {
  const title = extractTitle(html) ?? "Class (unknown)";
  const { kind, name: titleName } = parseTitle(title);
  // The h1 title always carries the full dotted name (nested types like
  // `SandboxOptions.ZombieConfig`). Generic types append `<...>` to the h1
  // text — the FQN must not include it.
  const name = titleName.split("<")[0].trim();

  const declaration = extractDeclaration(html);
  const packageName = declaration?.package ?? relDir;
  const fullyQualifiedName =
    packageName.length > 0 ? `${packageName}.${name}` : name;

  const signature = (extractTypeSignature(html) ?? "")
    .replace(/\s+/g, " ")
    .trim();
  const { superclass, interfaces } = parseExtendsImplements(signature);
  const inheritance = extractInheritance(html);
  const source = extractAboutLanguage(html) ?? "JavaDocs";
  const version = source.match(/\b(\d+\.\d+(?:\.\d+)?)\b/)?.[1];

  // Class-level description lives in the class-description section.
  let description: string | undefined;
  let deprecated = false;
  const classDesc = extractBalanced(
    html,
    /<section class="class-description"/i,
  );
  if (classDesc) {
    description = extractBlockText(classDesc.content) ?? undefined;
    deprecated = classDesc.content.includes("deprecated-label");
  }

  const fields: JavaDocMember[] = [];
  const constructors: JavaDocMember[] = [];
  const methods: JavaDocMember[] = [];
  const detailGroups = /<section class="([a-z-]+-details)" id="([^"]+)"/gi;
  let group: RegExpExecArray | null;
  while ((group = detailGroups.exec(html)) !== null) {
    const memberKind = groupKind(group[2]);
    if (memberKind === null) continue;
    const section = extractBalanced(
      html,
      new RegExp(`<section class="${group[1]}" id="${group[2]}"`, "i"),
      group.index,
    );
    if (!section) continue;
    const details = /<section class="detail"/g;
    let detail: RegExpExecArray | null;
    while ((detail = details.exec(section.content)) !== null) {
      const memberSection = extractBalanced(
        section.content,
        /<section class="detail"/,
        detail.index,
      );
      if (!memberSection) continue;
      const member = parseMemberDetail(memberSection.content, memberKind);
      if (member && member.signature.length > 0) {
        (memberKind === "field"
          ? fields
          : memberKind === "constructor"
            ? constructors
            : methods
        ).push(member);
      }
    }
  }

  return {
    name,
    package: packageName,
    kind,
    fullyQualifiedName,
    modifiers: signature.split(/\s+/)[0] ?? "",
    signature,
    inheritance,
    ...(superclass !== undefined ? { superclass } : {}),
    interfaces,
    ...(description !== undefined ? { description } : {}),
    ...(deprecated ? { deprecated: true } : {}),
    fields,
    constructors,
    methods,
    source,
    ...(version !== undefined ? { version } : {}),
    filePath,
  };
}
