/**
 * Unit tests for ScriptGenerator: template selection for every supported
 * type, balance scaling, and module wrapping.
 * Runs against the compiled dist/ build.
 *
 * Covers the freebuff fix: 'fixing' and 'sound' previously had no template
 * and generateScript threw "No template found" for them.
 */
import path from 'path';
import fs from 'fs';
import os from 'os';

import { DatabaseManager } from '../../dist/database/DatabaseManager.js';
import { ScriptGenerator } from '../../dist/generators/ScriptGenerator.js';

describe('ScriptGenerator', () => {
  let tmpDir;
  let db;
  let generator;

  beforeAll(async () => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'pz-gen-'));
    db = new DatabaseManager(path.join(tmpDir, 'data', 'pz_database.db'));
    await db.initialize();
    generator = new ScriptGenerator(db);
  });

  afterAll(() => {
    db.close();
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  test('generates an item script wrapped in a module', async () => {
    const script = await generator.generateScript(
      'item',
      'TestAxe',
      { Type: 'Weapon', DisplayName: 'Test Axe', MaxDamage: 2.5 },
      'MyMod',
    );
    expect(script).toContain('module MyMod');
    expect(script).toContain('item TestAxe');
    expect(script).toContain('DisplayName = Test Axe,');
    expect(script).toContain('MaxDamage = 2.5,');
  });

  test('balance=powerful scales weapon stats (MaxDamage 1.0 -> 1.5)', async () => {
    // category: 'Weapon' picks the melee_weapon template (base MaxDamage 1.0)
    const script = await generator.generateScript(
      'item',
      'BalancedKnife',
      { Type: 'Weapon', DisplayName: 'Balanced Knife', category: 'Weapon' },
      'Base',
      { balance: 'powerful' },
    );
    expect(script).toContain('MaxDamage = 1.5');
    // category is a template-selection hint, not a PZ property — must not leak
    expect(script).not.toContain('category = Weapon');
  });

  test('uncategorized item uses the tool template, not food (template-pick fix)', async () => {
    const script = await generator.generateScript('item', 'PlainTool', {
      Type: 'Normal',
      DisplayName: 'Plain Tool',
    });
    expect(script).toContain('item PlainTool');
    expect(script).toContain('Categories = Tool,'); // tool_item template
    expect(script).not.toContain('HungerChange'); // would come from food template
  });

  test('generates a recipe with ingredients and result', async () => {
    const script = await generator.generateScript('recipe', 'Make Plank', {
      ingredients: [{ item: 'Base.Log', count: 4 }],
      result: 'Base.Plank',
    });
    expect(script).toContain('recipe Make Plank');
    expect(script).toContain('Base.Log=4,');
    expect(script).toContain('Result:Base.Plank=1,');
  });

  test('generates an evolved recipe', async () => {
    const script = await generator.generateScript('evolvedrecipe', 'TestSoup', {
      baseItem: 'Base.TinPot',
      ingredients: ['Base.Water', 'Base.Cabbage'],
    });
    expect(script).toContain('evolvedrecipe TestSoup');
    expect(script).toContain('BaseItem: Base.TinPot');
    expect(script).toContain('Ingredients: Base.Water, Base.Cabbage');
  });

  test('generates a vehicle script', async () => {
    const script = await generator.generateScript('vehicle', 'TestCar', {
      Mass: 1200,
    });
    expect(script).toContain('vehicle TestCar');
    expect(script).toContain('Mass = 1200');
  });

  test('generates a fixing script (was: no template, threw)', async () => {
    const script = await generator.generateScript('fixing', 'Fix Axe', {
      require: 'Base.Axe',
      fixers: [{ material: 'Base.Screws', quantity: 2, skill: 'Maintenance', skillLevel: 2 }],
    });
    expect(script).toContain('fixing Fix Axe');
    expect(script).toContain('Require : Base.Axe,');
    expect(script).toContain('Fixer : Base.Screws=2; Maintenance=2,');
  });

  test('generates a sound script (was: no template, threw)', async () => {
    const script = await generator.generateScript('sound', 'TestAmbience', {
      category: 'Ambient',
      file: 'ambience.ogg',
      distanceMax: 50,
    });
    expect(script).toContain('sound TestAmbience');
    expect(script).toContain('category = Ambient,');
    expect(script).toContain('file = ambience.ogg,');
    expect(script).toContain('distanceMax = 50,');
  });

  test('includeComments emits the generated-by header with the correct repo URL', async () => {
    const script = await generator.generateScript(
      'item',
      'CommentedItem',
      { Type: 'Normal', DisplayName: 'Commented Item' },
      'Base',
      { includeComments: true },
    );
    expect(script).toContain('Generated by Project Zomboid MCP Server');
    expect(script).toContain('https://github.com/shakoorpour1991-sketch/pz-mcp-server');
  });
});
